In [1]:
import numpy as np

def vec_calc(a, b):
    # To-do
    a = np.array([a])
    b = np.array([b])
    return 5 * (a + b)
    
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(vec_calc([1, 2, 3], [4, 5, 6]))

[[25 35 45]]


In [2]:
import numpy as np

def mat_calc(A, B):
    # To-do
    return 5 * np.matmul(A, B)
    
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(mat_calc(np.array([[1, 2, 3], [4, 5, 6]]), np.array([[1, 2], [3, 4], [5, 6]])))

[[110 140]
 [245 320]]


In [3]:
import numpy as np

def n_diag(n):
    # To-do
    return np.diag(np.arange(1, n+1), k=0)
    
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(n_diag(3))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [4]:
import numpy as np

def mat_inv(A):
    # To-do
    # 1. 가역행렬인지 확인해보세요.
    # 2. 가역행렬이라면 역행렬을 반환해주세요.
    if A[0, 0] * A[1, 1] - A[0, 1] * A[1, 1] == 0:
        return None
    
    return np.linalg.inv(A)
    
	
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(mat_inv(np.array([[1, 2], [3, -1]])))

[[ 0.14285714  0.28571429]
 [ 0.42857143 -0.14285714]]


In [5]:
import numpy as np

def mat_solve(A, y):
    # To-do
    # 역행렬을 만들어서 A의 역행렬과 y를 곱하여 반환해보세요.
    return np.matmul(np.linalg.inv(A), y)
        
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(mat_solve(np.array([[1, 2], [3, -1]]), np.array([[1], [0]])))

[[0.14285714]
 [0.42857143]]


In [6]:
import numpy as np

def conv2d(I, K):
    # To-do
    # 1. 이미지와 커널의 합성곱을 한 후, 그 결과에 해당하는 크기를 가진 빈 행렬을 만들어보세요.
    Ih, Iw = I.shape
    Kh, Kw = K.shape
    rh, rw = Ih - Kh + 1, Iw - Kw +1
    result = np.zeros([rh, rw])
    
    # 2. 컨볼루션 연산을 위한 반복문을 선언해보세요.
    # 3. I의 부분행렬(Kh * Kw)과 K의 합성곱을 한 후, 모두 더한 값을 새로운 행렬로 만들어보세요.
    for y in range(rh):
        for x in range(rw):
            t = I[y:y+Kh, x:x+Kw] * K
            result[y, x] = np.sum(t)
    
    # 4. 결과를 반환해보세요.
    return result
    
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(conv2d(np.array([[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [1, 0, 0, 1]]), np.array([[1, -1], [1, -1]])))

[[-1. -1.  0.]
 [ 0. -1. -1.]
 [ 1.  0. -2.]]


In [7]:
import numpy as np

def dot(a, b):
    # To-do
    # numpy의 dot은 두 배열의 내적곱을 구하는 함수로, 
    # np.dot(array1, array2)의 방식으로 사용할 수 있습니다.
    # 이를 활용하여 배열 a와 b의 내적곱을 구하고 이를 반환해보세요.
    return np.dot(a, b)
    
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(dot([1, 2, 3], [4, 5, 6]))

32


In [8]:
import numpy as np

def mat_coord(m, n):
    # To-do
    result = np.zeros([m, n])
    m, n = int(m/2), int(n/2)
    
    result[:m, n:] = 1
    result[:m, :n] = 2
    result[m:, :n] = 3
    result[m:, n:] = 4

    return result
    
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(mat_coord(2, 2))
print(mat_coord(4, 4))

[[2. 1.]
 [3. 4.]]
[[2. 2. 1. 1.]
 [2. 2. 1. 1.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [9]:
import numpy as np

def is_symmetric(A):
    # To-do
    return np.allclose(A, A.T)
    
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(is_symmetric(np.array([[1, 2], [2, 3]])))

True


In [10]:
import numpy as np

def transform(v):
    # To-do
    array = np.identity(3)
    array = np.matmul(array, v)

    # 1. y축 대칭
    a = np.array([[-1, 0, 0], [0, 1, 0], [0, 0, 1]])
    array = np.matmul(a, array)

    # 2. 시계 방향으로 90도 회전
    # ( (cos (-90), -sin(-90)),  (sin(-90), cos(-90) ) 을 곱해준다.
    a = np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]])
    array = np.matmul(a, array)

    # 3. x축으로 2배 확대
    a = np.array([[2, 0, 0], [0, 1, 0], [0, 0, 1]])
    array = np.matmul(a, array)

    return array


# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(transform(np.array([[1], [2], [1]])))

[[4.]
 [1.]
 [1.]]


In [11]:
import numpy as np

def conv_size(I, K, p, s):
    # To-do
    ih, iw = I
    kh, kw = K
    ph, pw = p
    sh, sw = s

    rh = ( (ih + 2*ph - kh) / sh ) + 1 
    rw = ( (iw + 2*pw - kw) / sw ) + 1

    return rh, rw
    
# 결과 출력을 위한 코드입니다. 자유롭게 값을 바꿔보며 확인해보세요.
print(conv_size((5, 5), (3, 3), (0, 0), (1, 1)))

(3.0, 3.0)
